# Generated by Django 3.1.2 on 2020-10-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cochesVendidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_revision', models.IntegerField()),
                ('cambio_aceite', models.BooleanField(default=False)),
                ('cambio_filtro', models.BooleanField(default=False)),
                ('revision_frenos', models.BooleanField(default=False)),
                ('Otros', models.CharField(max_length=100)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cochesVendidos.cochesvendidos')),
            ],
        ),
    ]
